name: Release Packages

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  build:
    name: ${{ matrix.arch }}-${{ matrix.release }} build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - aarch64_generic
          - x86_64
        release:
          - openwrt-23.05

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.release }}
          FEEDNAME: mihomo
          ARTIFACTS_DIR: ${{ github.workspace }}/artifacts
          PACKAGES: luci-app-mihomo
          NO_REFRESH_CHECK: true

      - name: Compress
        run: |
          tar -c -z -f mihomo_${{ matrix.arch }}.tar.gz -C bin/packages/${{ matrix.arch }}/mihomo .
      
      - name: Delivering Package
        uses: actions/upload-artifact@v3
        with:
          name: mihomo-${{ matrix.release }}_${{ matrix.arch }}
          path: ${{ github.workspace }}/artifacts/bin/packages/${{ matrix.arch }}/mihomo .
          
push_packages:
       needs: build_ipk
       name: Push Packages to Release
       permissions:
       contents: write  # To push a branch
       runs-on: ubuntu-latest
       steps:
       - name: Download temporary artifact
         uses: actions/download-artifact@v3
        
       - name: Moving artifact to releases
         shell: bash
         run: |
          mkdir ./release
          cp -rf ./mihomo-23.05.4_x86_64/mihomo* ./release/mihomo.tar.gz
        
       - name: Upload release asset
         uses: svenstaro/upload-release-action@v2
         with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./release/*
          overwrite: true
          tag: luci-app-mihomo_${{ inputs.version }}
          file_glob: true
          body: |
            # LUCI APP NEKO ${{ inputs.version }}
            Simple Clash TUN based Proxy
            ### Information
            - Changelog : 
              - ${{ inputs.changelog }}
            - Default Config : 
              - config.yaml : minimal Configs for Neko (only 1 rules) - Secret : ` sign `
              - nosignals.yaml : 2 rules can added (Block Host, Game) - Secret : ` telekulo `
            ### Dependency Requirement
            - ` bash, kmod-tun, php, php-cgi ` (install PHP Manually before install Neko)
            - Openwrt 23: ` php8 php8-
            ### Information
